parameters:
#    rigauxt_alumni.example.class: Rigauxt\AlumniBundle\Example
    rigauxt_tools.twig.rigauxt_extension.class: Rigauxt\AlumniBundle\Twig\RigauxtExtension

services:
#    rigauxt_alumni.example:
#        class: %rigauxt_alumni.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    rigauxt_tools.twig.rigauxt_extension:
        class: '%rigauxt_tools.twig.rigauxt_extension.class%'
        arguments: ['@service_container']
        tags:
          - { name: twig.extension }
