parameters:
#    rigauxt_news.example.class: Rigauxt\NewsBundle\Example

services:
#    rigauxt_news.example:
#        class: %rigauxt_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
