<?php

namespace Rigauxt\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function getNbArticles()
	{
		$queryBuilder = $this->_em->createQueryBuilder()
							 	->select("count(alumni_article.id)")
							 	->from($this->_entityName, "alumni_article");
		$retour = $queryBuilder->getQuery()->getSingleScalarResult();
		return $retour;
	}
}
