parameters:
#    rigauxt_forum.example.class: Rigauxt\ForumBundle\Example

services:
#    rigauxt_forum.example:
#        class: %rigauxt_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
