<?php

namespace Rigauxt\AlumniBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function getNbNews()
	{
		$queryBuilder = $this->_em->createQueryBuilder()
							 	->select("count(alumni_news.id)")
							 	->from($this->_entityName, "alumni_news");
		$retour = $queryBuilder->getQuery()->getSingleScalarResult();
		return $retour;
	}
}
